const envVars = {
  REACT_APP_FIREBASE_API_KEY: process.env.REACT_APP_FIREBASE_API_KEY || "",
  REACT_APP_FIREBASE_AUTH_DOMAIN:
    process.env.REACT_APP_FIREBASE_AUTH_DOMAIN || "",
  REACT_APP_FIREBASE_FIREBASE_DB_URL:
    process.env.REACT_APP_FIREBASE_FIREBASE_DB_URL || "",
  REACT_APP_FIREBASE_FIREBASE_PROJEXT_ID:
    process.env.REACT_APP_FIREBASE_FIREBASE_PROJEXT_ID || "",
  REACT_APP_CLOUDINARY_PRESET: process.env.REACT_APP_CLOUDINARY_PRESET || "",
  REACT_APP_CLOUDINARY_URL: process.env.REACT_APP_CLOUDINARY_URL || "",
};

export { envVars };
